# Generated by Django 5.2.8 on 2025-11-28 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre de la Publicité')),
                ('store_name', models.CharField(max_length=100, verbose_name='Nom de la Boutique/Service')),
                ('image', models.ImageField(blank=True, default='boutiques/boutique.png', null=True, upload_to='advertisement_banners/', verbose_name='Image de la Boutique')),
                ('target_url', models.URLField(blank=True, null=True, verbose_name='Lien Clic (vers site ou téléphone)')),
                ('start_date', models.DateField(verbose_name='Date de début de publication')),
                ('end_date', models.DateField(verbose_name='Date de fin de publication')),
                ('category_target', models.CharField(blank=True, max_length=100, null=True, verbose_name='Catégorie Ciblée (Ex: Plombier)')),
                ('city_target', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville Ciblée')),
                ('is_active', models.BooleanField(default=True, verbose_name='Publicité Active')),
                ('priority', models.IntegerField(default=1, verbose_name="Priorité d'Affichage (1-10)")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Publicité',
                'verbose_name_plural': 'Publicités',
                'ordering': ['-priority', 'store_name'],
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('sous_category', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('phone', models.CharField(max_length=15)),
                ('whatsapp_number', models.CharField(blank=True, max_length=15, null=True)),
                ('bio', models.TextField()),
                ('image', models.ImageField(blank=True, default='workers_images/personne.jpg', null=True, upload_to='workers_images/')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude du lieu de travail')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude du lieu de travail')),
                ('is_active', models.BooleanField(default=True, verbose_name="Actif (Visible dans l'App)")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière Modification')),
            ],
        ),
    ]
