# Generated by Django 5.2.8 on 2025-11-24 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='email',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='icon_name',
        ),
        migrations.AddField(
            model_name='worker',
            name='image_url',
            field=models.URLField(default='http://192.168.1.23/:8000/static/images/personne.jpg', max_length=255),
        ),
        migrations.AddField(
            model_name='worker',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
