# Generated by Django 5.2.8 on 2025-12-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='image1',
            field=models.ImageField(blank=True, default='boutiques/boutique.png', null=True, upload_to='advertisement_banners/', verbose_name='Image de la Boutique1'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='image2',
            field=models.ImageField(blank=True, default='boutiques/boutique.png', null=True, upload_to='advertisement_banners/', verbose_name='Image de la Boutique2'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='image3',
            field=models.ImageField(blank=True, default='boutiques/boutique.png', null=True, upload_to='advertisement_banners/', verbose_name='Image de la Boutique3'),
        ),
    ]
