# Generated by Django 5.2.8 on 2025-11-24 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers_api', '0002_remove_worker_email_remove_worker_icon_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='image_url',
            field=models.URLField(default='static/images/personne.jpg', max_length=255),
        ),
    ]
