# Generated by Django 5.2.8 on 2025-11-24 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers_api', '0003_alter_worker_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='image_url',
            field=models.URLField(default='http://192.168.1.23/:8000/static/images/personne.jpg', max_length=255),
        ),
    ]
