# Generated by Django 5.2.8 on 2025-11-24 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers_api', '0004_alter_worker_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='image_url',
        ),
        migrations.AddField(
            model_name='worker',
            name='image',
            field=models.ImageField(blank=True, default='workers_images/personne.jpg', null=True, upload_to='workers_images/'),
        ),
    ]
