# Generated by Django 5.2.8 on 2025-11-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers_api', '0005_remove_worker_image_url_worker_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude du lieu de travail'),
        ),
        migrations.AddField(
            model_name='worker',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude du lieu de travail'),
        ),
    ]
