# Generated by Django 5.2.8 on 2025-11-26 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers_api', '0006_worker_latitude_worker_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name="Actif (Visible dans l'App)"),
        ),
        migrations.AlterField(
            model_name='worker',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
    ]
