# Generated by Django 5.2.8 on 2025-11-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers_api', '0007_worker_is_active_alter_worker_id_alter_worker_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-01-01', verbose_name='Date de Création'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière Modification'),
        ),
    ]
